### ISSUE TITLE
用在子控制器时有问题，消失时，动画没法回到原来位置

### ISSUE THREAD

**Issue by ap0806109** [1271284056/JDPhotoBrowser#1]
用在子控制器时有问题，消失时，动画没法回到原来位置

**Comment by 1271284056** [comment]
恩，没考虑全面，我改改
发自网易邮箱大师
在2017年11月28日 15:43，frank 写道： 用在子控制器时有问题，消失时，动画没法回到原来位置

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/1271284056/JDPhotoBrowser","title":"1271284056/JDPhotoBrowser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/1271284056/JDPhotoBrowser"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"用在子控制器时有问题，消失时，动画没法回到原来位置 (#1)"}],"action":{"name":"View Issue","url":"https://github.com/1271284056/JDPhotoBrowser/issues/1"}}}

**Comment by 1271284056** [comment]
问题解决了
发自网易邮箱大师
在2017年11月28日 15:52，1271284056 写道： 
恩，没考虑全面，我改改
发自网易邮箱大师
在2017年11月28日 15:43，frank 写道： 用在子控制器时有问题，消失时，动画没法回到原来位置

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/1271284056/JDPhotoBrowser","title":"1271284056/JDPhotoBrowser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/1271284056/JDPhotoBrowser"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"用在子控制器时有问题，消失时，动画没法回到原来位置 (#1)"}],"action":{"name":"View Issue","url":"https://github.com/1271284056/JDPhotoBrowser/issues/1"}}}
