### ISSUE TITLE
还是有问题

### ISSUE THREAD

**Issue by ap0806109** [1271284056/JDPhotoBrowser#2]
我是在tableview的cell里面 嵌套了一个scrollview，里面又放了几个tableview，这几个tableview都是由单独的controller控制，可以横向滑动切换tableview ，看大图没问题，就是消失的时候，没法回到原位😂，我也看过你的源码，好像也没问题，就坐标转换的时候，老是拿不到对的视图位置坐标

**Comment by 1271284056** [comment]
我代码直接更新了，pods咋更新忘了，过几天看看笔记再更新pods，你直接下载zip先试试
发自网易邮箱大师
在2017年11月29日 08:51，frank 写道： 我是在tableview的cell里面 嵌套了一个scrollview，里面又放了几个tableview，这几个tableview都是由单独的controller控制，可以横向滑动切换tableview ，看大图没问题，就是消失的时候，没法回到原位😂

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/1271284056/JDPhotoBrowser","title":"1271284056/JDPhotoBrowser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/1271284056/JDPhotoBrowser"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"还是有问题 (#2)"}],"action":{"name":"View Issue","url":"https://github.com/1271284056/JDPhotoBrowser/issues/2"}}}

**Comment by ap0806109** [comment]
好的 谢谢

**Comment by 1271284056** [comment]
Pods更新好了 你试试
发自网易邮箱大师
在2017年11月29日 09:04，frank 写道： 好的 谢谢

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/1271284056/JDPhotoBrowser","title":"1271284056/JDPhotoBrowser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/1271284056/JDPhotoBrowser"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ap0806109 in #2: 好的 谢谢"}],"action":{"name":"View Issue","url":"https://github.com/1271284056/JDPhotoBrowser/issues/2#issuecomment-347717681"}}}

**Comment by 1271284056** [comment]
好久没维护了，今天改了不少，优化一些细节，更新在pods上了，你试试。发自网易邮箱大师
            在2017年11月29日 10:13，Jason Zhang 写道： 
Pods更新好了 你试试
发自网易邮箱大师
在2017年11月29日 09:04，frank 写道： 好的 谢谢

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/1271284056/JDPhotoBrowser","title":"1271284056/JDPhotoBrowser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/1271284056/JDPhotoBrowser"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ap0806109 in #2: 好的 谢谢"}],"action":{"name":"View Issue","url":"https://github.com/1271284056/JDPhotoBrowser/issues/2#issuecomment-347717681"}}}
